"""Generate a Morris-White-Crowther zip (zipper) plot of CI coverage, in the
paper's pgfplots/Okabe-Ito house style, from the canonical simulation_baseline
per-replication output.

Each replication's CI is drawn as a horizontal segment, sorted (bottom-to-top)
by the absolute z-statistic against the estimand (the estimator's probability
limit). Covering intervals are blue, non-covering orange; the color switch height
IS the empirical coverage, so under-coverage shows as a switch below the dashed
95 line. Three panels: DML (in-sample PC), DML cross-fit PC, doubly-robust, at the
strong-effect / small-n cell where the IF interval under-covers most.

  python3 data/scripts/make_zip_plot.py            # -> paper/drafts_jbes_2026/fig_zip.tex
"""
import csv
import statistics as st
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RAW = REPO / "results" / "simulation_baseline" / "raw_replicates.csv"
COV = REPO / "results" / "simulation_baseline" / "coverage_table.csv"
OUT = REPO / "paper" / "drafts_jbes_2026" / "fig_zip.tex"

N = "500"
DGP = "scm1_0.10"
PANELS = [("DML", "(a) in-sample DML"),
          ("DML_cfpca", "(b) cross-fit DML"),
          ("DR", "(c) doubly-robust")]
COV_COLOR = "cNYC"
MISS_COLOR = "cSF"


def cell_rows(rows, estimator):
    return [r for r in rows
            if r["estimator"] == estimator and r["N"] == N and r["dgp"] == DGP]


def main():
    rows = list(csv.DictReader(open(RAW)))
    truth = {(r["estimator"], r["N"], r["dgp"]): float(r["truth"])
             for r in csv.DictReader(open(COV))}
    panels = []
    xlo, xhi = +1e9, -1e9
    for est, _title in PANELS:
        rs = cell_rows(rows, est)
        plim = truth[(est, N, DGP)]
        recs = []
        for r in rs:
            t, se = float(r["theta"]), float(r["se"])
            lo, hi = float(r["ci_low"]), float(r["ci_high"])
            z = (t - plim) / se if se > 0 else 0.0
            cov = lo < plim < hi
            recs.append((abs(z), lo, hi, cov))
            xlo, xhi = min(xlo, lo), max(xhi, hi)
        recs.sort(key=lambda x: x[0])
        n = len(recs)
        cover = 100.0 * sum(1 for x in recs if x[3]) / n
        seg = []
        for i, (_z, lo, hi, cov) in enumerate(recs):
            y = 100.0 * (i + 0.5) / n
            seg.append((lo, hi, y, cov))
        panels.append({"est": est, "plim": plim, "cover": cover, "seg": seg})

    xlo = max(xlo, -0.6)
    xhi = min(xhi, 0.6)

    L = []
    L.append("% AUTO-GENERATED by data/scripts/make_zip_plot.py -- do not hand-edit.")
    L.append("% Zip (zipper) plot of 95% CI coverage, simulation_baseline, "
             f"N={N}, {DGP}.")
    L.append(r"\begin{figure}[H]")
    L.append(r"\centering")
    L.append(r"\begin{tikzpicture}")
    for j, p in enumerate(panels):
        _est, title = PANELS[j]
        pos = "" if j == 0 else \
              f"at={{(zp{chr(64+j)}.east)}}, anchor=west, xshift=0.7cm,"
        ylab = r"ylabel={centile rank of $|z|$}," if j == 0 else "ylabel={},"
        ytl = "" if j == 0 else "yticklabels={,,,,,,},"
        leg = (r"legend style={font=\scriptsize, draw=none, fill=none, "
               r"at={(0.5,1.14)}, anchor=south, legend columns=2, "
               r"/tikz/every even column/.append style={column sep=10pt}},") if j == 1 else ""
        L.append(f"\\begin{{axis}}[")
        L.append(f"    causalre, {pos} name=zp{chr(65+j)},")
        L.append(f"    width=0.30\\textwidth, height=6.6cm,")
        L.append(f"    xmin={xlo:.3f}, xmax={xhi:.3f}, ymin=0, ymax=100,")
        L.append(f"    ytick={{0,25,50,75,95}}, xtick={{-0.4,0,0.4}},")
        L.append(f"    xlabel={{estimate}}, {ylab} {ytl}")
        L.append(f"    title={{{title}}},")
        if leg:
            L.append(f"    {leg}")
        L.append(f"]")
        L.append(r"\addplot[black, densely dashed, line width=0.5pt, forget plot] "
                 f"coordinates {{({xlo:.3f},95) ({xhi:.3f},95)}};")
        L.append(r"\addplot[cMUTE, line width=0.6pt, forget plot] "
                 f"coordinates {{({p['plim']:.4f},0) ({p['plim']:.4f},100)}};")
        first_cov = first_miss = (j == 0)
        for lo, hi, y, cov in p["seg"]:
            lo_c = max(lo, xlo); hi_c = min(hi, xhi)
            col = COV_COLOR if cov else MISS_COLOR
            tag = ""
            if cov and first_cov:
                pass
            L.append(f"\\draw[{col}, line width=0.32pt] "
                     f"(axis cs:{lo_c:.4f},{y:.3f}) -- (axis cs:{hi_c:.4f},{y:.3f});")
        if j == 1:
            L.append(r"\addlegendimage{cNYC, line width=1.2pt}\addlegendentry{covers}")
            L.append(r"\addlegendimage{cSF, line width=1.2pt}\addlegendentry{misses}")
        L.append(f"\\node[anchor=south west, font=\\scriptsize] at "
                 f"(axis cs:{xlo:.3f},2) {{cov.\\ {p['cover']:.0f}\\%}};")
        L.append(r"\end{axis}")
    L.append(r"\end{tikzpicture}")
    cap = (r"\caption{Zip plot of nominal $95\%$ confidence-interval coverage "
           r"\citep{morris2019using} at the strong-effect, small-sample cell "
           f"($n={N}$, per-$\\sigma$ direct effect $0.10$), $300$ replications. "
           r"Each horizontal segment is one replication's interval, sorted "
           r"bottom-to-top by the absolute $z$-statistic against the estimand "
           r"(the estimator's probability limit, gray vertical line); intervals "
           r"that cover the estimand are blue and those that miss are orange, so "
           r"the height at which the colour switches is the empirical coverage. "
           r"The doubly-robust interval switches at the dashed nominal $95$ line, "
           r"the cross-fit DML interval close to it, and the in-sample DML "
           r"influence-function interval well below it: its misses are too "
           r"frequent and fan out symmetrically, the visual signature of an "
           r"anticonservative variance rather than bias.}")
    L.append(cap)
    L.append(r"\label{fig:sim-coverage}")
    L.append(r"\end{figure}")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)} lines)")
    for p in panels:
        print(f"  {p['est']:10} plim={p['plim']:+.4f} coverage={p['cover']:.1f}%")


if __name__ == "__main__":
    main()
